localhost

[all:vars]
ethereum_network_name=epbs-devnet-0

[bootnode]
bootnode-1 ansible_host=91.98.233.229 ipv6=2a01:4f8:1c1b:a965::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True 

[lighthouse_geth]
lighthouse-geth-1 ansible_host=178.104.16.27 ipv6=2a01:4f8:1c19:8f71::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=200
lighthouse-geth-2 ansible_host=65.21.245.12 ipv6=2a01:4f9:c014:dcaf::1 cloud=hetzner cloud_region=hel1-dc2 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=200 validator_end=400
lighthouse-geth-3 ansible_host=195.201.39.213 ipv6=2a01:4f8:1c19:d1fe::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=600

[lodestar_geth]
lodestar-geth-1 ansible_host=128.140.69.39 ipv6=2a01:4f8:1c19:5720::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1200 validator_end=1400
lodestar-geth-2 ansible_host=89.167.119.3 ipv6=2a01:4f9:c014:ecb8::1 cloud=hetzner cloud_region=hel1-dc2 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1400 validator_end=1600
lodestar-geth-3 ansible_host=91.107.234.234 ipv6=2a01:4f8:1c1e:c632::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1600 validator_end=1800

[nimbus_geth]
nimbus-geth-1 ansible_host=116.203.40.15 ipv6=2a01:4f8:1c1c:ad4d::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=1850 validator_end=1900

[prysm_geth]
prysm-geth-1 ansible_host=178.104.5.127 ipv6=2a01:4f8:1c19:38ee::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=600 validator_end=800
prysm-geth-2 ansible_host=89.167.115.65 ipv6=2a01:4f9:c014:dea5::1 cloud=hetzner cloud_region=hel1-dc2 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=800 validator_end=1000
prysm-geth-3 ansible_host=128.140.15.196 ipv6=2a01:4f8:c0c:5ac3::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1200

[teku_geth]
teku-geth-1 ansible_host=116.203.62.101 ipv6=2a01:4f8:c0c:8b2b::1 cloud=hetzner cloud_region=nbg1-dc3 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=1800 validator_end=1850


[lighthouse_reth]

# Consensus client groups

[lighthouse:children]
lighthouse_geth
[lodestar:children]
lodestar_geth
[nimbus:children]
nimbus_geth
[teku:children]
teku_geth
[prysm:children]
prysm_geth
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
lighthouse_geth
lodestar_geth
nimbus_geth
prysm_geth
teku_geth
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]
[ethrex:children]

# Global groups

[consensus_node:children]
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
geth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
